### ISSUE TITLE
Can't hide menu bar

### ISSUE THREAD

**Issue by josswright** [dogancelik/atomic-tweetdeck#1]
It would amazing if there were an option to hide the menu bar at the top.

**Comment by dogancelik** [comment]
Can you try [this build](https://github.com/dogancelik/atomic-tweetdeck/releases/tag/v0.11.0)?

You need to check:
![hide menu](https://user-images.githubusercontent.com/486818/50572738-f8836080-0dd7-11e9-86ee-3df2f840c3f4.png)

**Comment by innir** [comment]
Works for me but the menu is only hidden after reopening the app. Adding a shortcut to toggle this would be nice too.

**Comment by dogancelik** [comment]
Fixed in cba91b8269c58fe94ee87fe5bc0479cfd5ff5d06
