### ISSUE TITLE
Issue with column alignment

### ISSUE THREAD

**Issue by zauberparacelsus** [dogancelik/atomic-tweetdeck#6]
I am seeing an issue with the columns sometimes becoming vertically misaligned from the top of the interface.  No misalignment occurs when running Tweetdeck inside of a browser (in my case, Vivaldi, a chrome-based browser).

Screenshot of the issue:
![image](https://user-images.githubusercontent.com/548168/106630169-99115500-6549-11eb-9382-cce0e9edc2ae.png)

A small amount of misalignment occurs when expanding a tweet and then clicking "Back to X" at the top of the column, though I do not recall what caused the larger amount of misalignment shown in the screenshot.  If I manage to reproduce the issue again, I'll update this bug report.

**Comment by dogancelik** [comment]
Yup I can reproduce this, maybe has to do with Electron version 9.x, I will try with the newer versions 10 and 11.

Edit: It does not occur in version 10 but I need to fix some errors before upgrading to Electron 10.

**Comment by zauberparacelsus** [comment]
I'm guessing that it bundles its own version of electron, rather than using the system's installed version of Electron?  Because Manjaro uses version 10.3

**Comment by dogancelik** [comment]
Can you try [this version](https://github.com/dogancelik/atomic-tweetdeck/releases/tag/v0.15.0)?

I updated Electron to version 10 in this build.

**Comment by zauberparacelsus** [comment]
The issue appears to be resolved now!

**Comment by dogancelik** [comment]
Thank you for your confirmation!
